Using action.yaml
Signed-off-by: Yehudit Kerido <yehudit.kerido@nokia.com>

diff --git a/.github/workflows/sdk-e2e-tests-with-papermill.yaml b/.github/workflows/sdk-e2e-tests-with-papermill.yaml
--- a/.github/workflows/sdk-e2e-tests-with-papermill.yaml
+++ b/.github/workflows/sdk-e2e-tests-with-papermill.yaml
@@ -5,54 +5,76 @@ on:
   pull_request: {}
   workflow_dispatch: {}
 
-jobs:
-  run-experiment:
-    runs-on: ubuntu-latest
+concurrency:
+  group: ${{ github.workflow }}-${{ github.ref }}
+  cancel-in-progress: true
 
+jobs:
+  create-katib-notebooks-test:
+    runs-on: ubuntu-latest
+    timeout-minutes: 30
+    strategy:
+      fail-fast: false
+      matrix:
+        python-version: ["3.9", "3.10", "3.11"]
     steps:
-      - name: Checkout repository
+      - name: Checkout
         uses: actions/checkout@v4
 
-      - name: Set up Python
-        uses: actions/setup-python@v5
+      - name: Test Notebook
+        uses: ./.github/workflows/template-notebook-test
         with:
-          python-version: '3.9'
+          python-version: ${{ matrix.python-version }}
+          notebook-input: "examples/v1beta1/sdk/cmaes-and-resume-policies.ipynb,examples/v1beta1/sdk/tune-train-from-func.ipynb"
 
-      - name: Setup Minikube Cluster
-        shell: bash
-        run: ./test/e2e/v1beta1/scripts/gh-actions/setup-minikube.sh true true "" "" "cmaes"
+#  run-experiment:
+#    runs-on: ubuntu-latest
+#
+#    steps:
+#      - name: Checkout repository
+#        uses: actions/checkout@v4
 
-      - name: Setup Katib
-        shell: bash
-        run: ./test/e2e/v1beta1/scripts/gh-actions/setup-katib.sh true true postgres
+#      - name: Set up Python
+#        uses: actions/setup-python@v5
+#        with:
+#          python-version: '3.9'
+
+#      - name: Setup Minikube Cluster
+#        shell: bash
+#        run: ./test/e2e/v1beta1/scripts/gh-actions/setup-minikube.sh true true "" "" "cmaes"
+
+#      - name: Setup Katib
+#        shell: bash
+#        run: ./test/e2e/v1beta1/scripts/gh-actions/setup-katib.sh true true postgres
 
 
-      - name: Install dependencies
-        run: |
-          python -m pip install --upgrade pip
-          pip install papermill kubeflow-katib jupyter ipykernel
-          python -m ipykernel install --user --name python3 --display-name "Python 3"
-      - name: Set Up Environment
-        shell: bash
-        run: |
-          # Define the experiments as a comma-separated string
-          # tune-train-from-func.ipynb Already tested, later will be added
-          EXPERIMENTS="cmaes-and-resume-policies.ipynb,tune-train-from-func.ipynb"  
-          echo "EXPERIMENTS=$EXPERIMENTS" >> $GITHUB_ENV
-          echo "experiments are = $EXPERIMENTS"
+#      - name: Install dependencies
+#        run: |
+#          python -m pip install --upgrade pip
+#          pip install papermill kubeflow-katib jupyter ipykernel
+#          python -m ipykernel install --user --name python3 --display-name "Python 3"
+#
+#      - name: Set Up Environment
+#        shell: bash
+#        run: |
+#          # Define the experiments as a comma-separated string
+#          # tune-train-from-func.ipynb Already tested, later will be added
+#          EXPERIMENTS="cmaes-and-resume-policies.ipynb,tune-train-from-func.ipynb"
+#          echo "EXPERIMENTS=$EXPERIMENTS" >> $GITHUB_ENV
+#          echo "experiments are = $EXPERIMENTS"
 
-      - name: Run experiments with Papermill
-        shell: bash
-        run: |
-          IFS=',' read -r -a EXP_ARRAY <<< "$EXPERIMENTS"
-          # Loop through each experiment notebook
-          for EXP in "${EXP_ARRAY[@]}"; do
-            echo "Running experiment: $EXP"
-            papermill "examples/v1beta1/sdk/$EXP" "examples/v1beta1/sdk/${EXP%.ipynb}_output.ipynb" --log-output --kernel python3 || {
-                echo "Papermill failed for experiment: $EXP"
-                exit 1
-            }
-          done
+#      - name: Run experiments with Papermill
+#        shell: bash
+#        run: |
+#          IFS=',' read -r -a EXP_ARRAY <<< "$EXPERIMENTS"
+#          # Loop through each experiment notebook
+#          for EXP in "${EXP_ARRAY[@]}"; do
+#            echo "Running experiment: $EXP"
+#            papermill "examples/v1beta1/sdk/$EXP" "examples/v1beta1/sdk/${EXP%.ipynb}_output.ipynb" --log-output --kernel python3 || {
+#                echo "Papermill failed for experiment: $EXP"
+#                exit 1
+#            }
+#          done
 #      - name: Run experiment
 #        run: |
 #          chmod +x ./test/e2e/v1beta1/scripts/gh-actions/run-e2e-sdk-tests-papermill.sh
